(TeX-add-style-hook
 "ASORA"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("book" "oneside" "10pt" "")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("inputenc" "utf8") ("fontenc" "T1") ("titlesec" "explicit" "newparttoc" "pagestyles") ("hyperref" "hyperfootnotes=false")))
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "latex2e"
    "snapshot"
    "book"
    "bk10"
    "geometry"
    "ifthen"
    "etoolbox"
    "ifxetex"
    "ifluatex"
    "graphicx"
    "xcolor"
    "tcolorbox"
    "fixltx2e"
    "xstring"
    "chngcntr"
    "xltxtra"
    "realscripts"
    "inputenc"
    "fontspec"
    "polyglossia"
    "lmodern"
    "fontenc"
    "microtype"
    "amsmath"
    "amscd"
    "amssymb"
    "titlesec"
    "titletoc"
    "qrcode"
    "enumitem"
    "imakeidx"
    "hyperref"
    "extpfeil")
   (TeX-add-symbols
    '("abs" 1)
    '("dfdx" 2)
    '("dx" 1)
    '("lititle" 1)
    '("terminology" 1)
    '("alert" 1)
    '("mono" 1)
    "divisionfont"
    "blocktitlefont"
    "contentsfont"
    "pagefont"
    "tabularfont"
    "xreffont"
    "titlepagefont"
    "divisionnameptx"
    "titleptx"
    "subtitleptx"
    "shortitleptx"
    "authorsptx"
    "epigraphptx"
    "genericpreview"
    "phantomsection"
    "qedhere"
    "imp"
    "eps"
    "unif"
    "ptwise"
    "CC"
    "DD"
    "RR"
    "QQ"
    "NN"
    "ZZ"
    "lt"
    "gt"
    "amp"
    "limit")
   (LaTeX-add-labels
    "#6"
    "g:fn:idp2"
    "g:fn:idp3"
    "x:mrow:eq_QForm1"
    "x:mrow:eq_QForm2"
    "x:mrow:eq_QForm3"
    "g:mrow:idp4"
    "x:mrow:eq_QForm4"
    "g:fn:idp5"
    "g:fn:idp6"
    "x:men:eq_GenCubic"
    "g:fn:idp7"
    "x:mrow:eq_LagrangeQuadratic1"
    "x:mrow:eq_LagrangeQuadratic2"
    "g:fn:idp12"
    "g:fn:idp22"
    "g:fn:idp34"
    "x:men:eq_LeibnizProductRule"
    "x:men:eq_prodruleinc"
    "x:men:eq_prodruledec"
    "g:fn:idp39"
    "x:men:eq_brach_vel"
    "x:mrow:eq_Brachistochrone"
    "g:fn:idp42"
    "x:mrow:eq_ExponentAdditionProperty"
    "x:men:eq_BinomialSeries"
    "x:men:eq_CauchyCounterEx"
    "x:men:PDE_sol"
    "g:fn:idp106"
    "g:fn:idp114"
    "x:task:prob_Taylor_Series-using-c"
    "g:fn:idp136"
    "x:men:eq_LagRem1"
    "x:men:eq_LagRem2"
    "x:men:eq_LagRem3"
    "g:fn:idp145"
    "x:mrow:xsin1x"
    "g:fn:idp203"
    "g:fn:idp260"
    "g:fn:idp267"
    "g:fn:idp304"
    "g:fn:idp311"
    "x:men:eq_NIP-interval"
    "g:fn:idp313"
    "g:fn:idp319"
    "g:fn:idp335"
    "g:fn:idp342"
    "g:fn:idp343"
    "g:fn:idp350"
    "g:fn:idp351"
    "g:fn:idp352"
    "g:fn:idp353"
    "g:fn:idp357"
    "g:fn:idp358"
    "g:fn:idp363")
   (LaTeX-add-bibitems
    "x:biblio:bradley09__cauch_cours"
    "x:biblio:dunham90__journ_throug_genius"
    "x:biblio:franks10__cantor_other_proof_rr_uncoun"
    "x:biblio:grabiner81__origin_cauch_rigor_calculy"
    "x:biblio:hawking05__god_creat_integ"
    "x:biblio:jahnke03__histor_analy"
    "x:biblio:landau66__found_analy"
    "x:biblio:levenson09__newton_count"
    "x:biblio:netz07__archim_codex"
    "x:biblio:newton45__sir_isaac_two_treat_quadr"
    "x:biblio:Bernoulli_bio_mactutor"
    "x:biblio:robinson74__non_stand_analy"
    "x:biblio:russo96__forgot_revol"
    "x:biblio:sandifer07__early_mathem_leonar_euler"
    "x:biblio:struik69__sourc_book_mathem"
    "x:biblio:thurston56__number_system")
   (LaTeX-add-environments
    "acknowledgement"
    "chapterptx"
    "sectionptx"
    "partptx"
    "subsectionptx"
    "indexptx"
    "introduction"
    "sidebyside")
   (LaTeX-add-index-entries
    "Leibniz, Gottfried Wilhelm"
    "Cardano, Girolomo"
    "Quadratic Formula!second proof"
    "Fermat's Little Theorem!problems leading to!if a prime divides a product of two numbers then it divides one of the factors"
    "Fermat's Little Theorem!problems leading to!if a prime divides an arbitrary product then it divides one of the factors"
    "Fermat's Little Theorem!problems leading to!if \\(p\\) is prime then \\(p\\) divides \\(p \\choose{}k\\)"
    "Fermat's Little Theorem"
    "\\(\\QQ\\)!rational numbers exist between rational numbers"
    "common denominators"
    "\\(\\sqrt{2}\\)!is irrational"
    "\\(\\sqrt{2}\\)!meaning of"
    "\\(\\RR\\)!real numbers exist between real numbers"
    "Archimedean Property"
    "Leibniz, Gottfried Wilhelm!and infinitesimals"
    "Lagrange, Joseph-Louis"
    "Newton, Isaac!foundation of calculus"
    "\\(\\QQ\\)!creating irrationals from rationals"
    "\\(\\RR\\)!irrational numbers"
    "\\(\\QQ\\)!is it possible to have two rational numbers, \\(a\\) and \\(b\\), such that \\(a^b\\) is irrational"
    "Leibniz, Gottfried Wilhelm!portrait of"
    "Leibniz, Gottfried Wilhelm!first calculus publication"
    "Newton, Isaac"
    "Leibniz, Gottfried Wilhelm!differentiation rules"
    "Newton, Isaac!portrait of"
    "differentiation!power rule with fractional exponents"
    "Bernoulli, Johann"
    "Brachistochrone problem, the"
    "Bernoulli, Johann!Bernoulli's challenge"
    "Bernoulli, Johann!portrait of"
    "Bernoulli Jacob"
    "Bernoulli, Johann!\\textit{\"Tanquam ex ungue leonem\"}"
    "Brachistochrone problem, the!Bernoulli's solution"
    "polynomials!infinite"
    "power series!definition of"
    "series!Geometric series!naive derivation"
    "\\(e^x\\)!\\(E(0)=1\\)"
    "\\(e^x\\)!\\(E(x+y)=E(x)E(y)\\)"
    "\\(e^x\\)!\\(E(m)=\\left(E(1)\\right)^mE(0)=1\\)"
    "\\(e^x\\)!\\(E(mx)=\\left(E(x\\right))^m\\)"
    "\\(e^x\\)!\\(E(-x)=\\left(E(x)\\right)^{-1}\\)"
    "\\(e^x\\)!\\(E(\\frac{1}{n})=\\left(E(1)\\right)^{1/n}\\)"
    "\\(e^x\\)!\\(E\\left(\\frac{m}{n}\\right)=\\left(E(1)\\right)^{m/n}\\)"
    "\\(e^x\\)!definition of \\(e\\)"
    "Binomial Series, the!squaring the"
    "series!graph the square root series"
    "\\(\\pi\\)!first series expansion"
    "\\(\\pi\\)!second series expansion"
    "series!Geometric series!differentiating"
    "Euler, Leonhard!portrait of"
    "series!Geometric series!alternating"
    "series!Geometric series!derivation of the series representation of \\(\\ln(1+x)\\) from"
    "power series!drills"
    "power series!for \\(a^x\\) expanded about 0"
    "power series!of \\(\\sin(x)\\), expanded about \\(a\\)"
    "\\(\\sin x\\)!as a power series"
    "Maclaurin series drills"
    "series!term by term integration of"
    "Taylor's Formula"
    "Taylor, Brook!portrait of"
    "Taylor, Brook"
    "Maclaurin, Colin"
    "Euler, Leonhard"
    "Lagrange, Joseph-Louis!portrait of"
    "Cauchy, Augustin"
    "Taylor's Formula!use to obtain the general binomial series"
    "\\(e^x\\)!Taylor's series for"
    "series!Taylor's series!expansion of \\(e^x, \\sin x\\), and \\(\\cos x\\)"
    "\\(\\sin x\\)!Taylor's series for"
    "\\(\\cos x\\)!Taylor's series for"
    "Taylor's Theorem"
    "series!Taylor's series!used to approximate \\(\\ln 2\\)"
    "Riemann, Bernhard"
    "series!Alternating Harmonic Series!rearrangements of"
    "series!Harmonic Series"
    "Fourier, Jean Baptiste Joseph!portrait of"
    "Fourier, Jean Baptiste Joseph"
    "Heat Equation, the"
    "Heat Equation, the!parameter \\(k\\) must be less than zero"
    "Heat Equation, the!solving for \\(\\xi(x)\\)"
    "Heat Equation, the!fundamental solutions of"
    "\\(\\sin x\\)!orthogonality of"
    "orthogonality!of \\(\\sin nx\\)"
    "Fourier Series!sine series of an odd function"
    "Fourier Series"
    "Fourier Series!divergent Fourier series example"
    "\\(\\cos (nx)\\)!orthogonality of"
    "orthogonality!of \\(\\cos nx\\)"
    "Fourier Series!computing the coefficients"
    "Fourier Series!cosine series!the Fourier cosine series of \\(f(x)=x-\\frac{1}{2}\\)"
    "sequences!convergence to zero"
    "absolute value"
    "convergence!of a sequence!convergence to zero drill"
    "limit!definition of non-existence"
    "sequences!convergence"
    "convergence!of a sequence"
    "limit!\\(\\lim_{n\\rightarrow\\infty}b^{\\left(\\frac{1}{n}\\right)}=1\\) if \\(b>0\\)"
    "limit!of a constant sequence"
    "sequences!constant sequences"
    "Triangle Inequalities"
    "Triangle Inequalities!Triangle Inequality"
    "Triangle Inequalities!Reverse Triangle Inequalitiy"
    "limit!termwise sums of"
    "sequences!termwise sums of"
    "limit!products of"
    "sequences!convergence of!convergent sequences are bounded"
    "sequences!termwise product of"
    "sequences!constant multiples of"
    "limit!of a constant times a sequence"
    "limit!quotients of"
    "sequences!termwise quotient of"
    "limit!identifing the theorems used in a limit"
    "limit!Squeeze Theorem for Sequences"
    "sequences!divergence of"
    "divergence!of a sequence"
    "sequences!divergence to \\(\\infty\\)"
    "\\(\\infty\\)!positive infinity!divergence to"
    "\\(\\infty\\)!negative infinity!divergence to"
    "\\(\\infty\\)!divergence to"
    "sequences!the sequence of positive integers diverges to infinity"
    "divergence!divergence to infinity implies divergence"
    "limit!of ratios of polynomials"
    "series!Taylor's series"
    "Triangle Inequalities!for Integrals"
    "series!Taylor's series!\\(f^{(n)}\\lt B,\\forall\\  n\\in\\NN\\imp\\) Taylor series converges"
    "\\(e^x\\)!\\(e^{a+b}=e^ae^b\\)"
    "Lagrange's form of the remainder"
    "Lagrange's form of the remainder!\\(x\\lt a\\)"
    "Intermediate Value Theorem (IVT)"
    "Extreme Value Theorem (EVT)"
    "series!Binomial Series, the"
    "Binomial Series, the!converges on the interval \\([0,1]\\)"
    "series!Binomial Series, the!Binomial Series is a Taylor series"
    "sequences!Cauchy sequences!Cauchy's remainder"
    "series!Taylor's series!Cauchy Remainder"
    "Binomial Series, the!\\(g(c)=\\frac{c-x}{1+c}\\) is increasing"
    "\\(g(c)=\\frac{c-x}{1+c}\\) is increasing on \\([x,0]\\)"
    "Cauchy, Augustin!portrait of"
    "Weierstrass, Karl!portrait of"
    "Weierstrass, Karl"
    "Bolzano, Bernhard"
    "Bolzano, Bernhard!portrait of"
    "continuity!definition of"
    "continuity"
    "Extreme Value Theorem (EVT)!continuity and"
    "continuity!Extreme Value Theorem (EVT) and"
    "Intermediate Value Theorem (IVT)!continuity and"
    "continuity!Intermediate Value Theorem and"
    "continuity!\\(f(x) = mx +b\\) is continuous everywhere"
    "continuity!\\(\\pm\\sqrt{x}\\) is continuous at zero"
    "\\(\\sqrt{x}\\)!is continuous at zero"
    "Halmos, Paul!portrait of"
    "Halmos, Paul"
    "Topologist's sine function!is continuous at zero"
    "continuity!via limits"
    "continuity!Heaviside's function is not continuous at zero"
    "limit!\\(\\limit{x}{a}{f(x)}=f(a)\\) implies \\(f(x)\\) is continuous"
    "continuous functions!sum of continuous functions is continuous"
    "continuous functions!the composition of continuous functions is continuous"
    "limit"
    "limit!properties of"
    "limit!verify limit laws from calculus"
    "Squeeze Theorem!for functions"
    "differentiation!definition of the derivative"
    "continuity!implied by differentiability"
    "differentiation!differentiability implies continuity"
    "Fermat's Theorem"
    "Fermat's Theorem!if \\(f(a)\\) is a maximum then \\(f^\\prime(a)=0\\)"
    "Fermat's Theorem!if \\(f(a)\\) is a minimum then \\(f^\\prime(a)=0\\)"
    "Mean Value Theorem, the"
    "Rolle's Theorem"
    "Extreme Value Theorem (EVT)!Rolle's Theorem, and"
    "differentiation!if \\(f^\\prime\\lt 0\\) on an interval then \\(f\\) is decreasing"
    "differentiation!\\(f^\\prime(a)>0\\) implies \\(f\\) is increasing nearby"
    "differentiation!\\(f^\\prime(a)\\lt 0\\) implies \\(f\\) is decreasing nearby"
    "continuity!formal definition of discontinuity"
    "Nested Interval Property (NIP)!endpoints"
    "limit!of interval endpoints in the NIP"
    "square roots exist"
    "Nested Interval Property (NIP)!square roots of integers, and"
    "Nested Interval Property (NIP)!implies the existence of square roots of integers"
    "series!Harmonic Series!slow divergence of"
    "Intermediate Value Theorem (IVT)!the case \\(f(a)\\leq v\\leq f(b)\\)"
    "Intermediate Value Theorem (IVT)!the case \\(f(a)\\geq v\\geq f(b)\\)"
    "polynomials!with odd degree must have a root"
    "Intermediate Value Theorem (IVT)!a polynomial with odd degree must have a root"
    "continuous functions!continuous function on a closed, bounded interval is bounded"
    "sequences!subsequences"
    "sequences!all subsequences of a convergent sequence converge"
    "Bolzano-Weierstrass Theorem"
    "Bolzano-Weierstrass Theorem (BWT)"
    "Bolzano-Weierstrass Theorem (BWT)!implies that a  continuous functions on a closed set is bounded"
    "continuous functions!on a closed set, and the Bolzano-Weierstrass Theorem"
    "continuity!Bolzano-Weierstrass Theorem implies a continuous function on a closed set is bounded"
    "Upper Bound"
    "Least Upper Bound Property (LUBP)"
    "Nested Interval Property (NIP)!implies the LUBP"
    "sequences!bounded and non-decreasing"
    "Bolzano-Weierstrass Theorem (BWT)!implies the NIP"
    "sequences!find a bounded sequence of rational numbers such that no subsequence converges to a rational number"
    "Least Upper Bound Property (LUBP)!implies the Nested Interval Property (NIP)"
    "Least Upper Bound Property (LUBP)!doesn't hold in \\(\\QQ\\)"
    "Archimedean Property!and \\(\\QQ\\)"
    "Greatest Lower Bound Property (GLBP)!definition of"
    "Least Upper Bound Property (LUBP)!identifying suprema and infima"
    "\\(b\\) is an upper bound of \\(S\\subseteq \\RR\\) if and only if \\(-b\\) is a lower bound of \\(-S\\)"
    "Abel, Niels Henrik"
    "Cauchy, Augustin!Cauchy's flawed proof that the limit of continuous functions is continuous"
    "continuity!Cauchy's flawed proof that the limit of continuous functions is continuous"
    "convergence!of a series!pointwise"
    "uniform convergence"
    "uniform convergence!continuous functions and"
    "continuous functions!uniform convergence and"
    "continuous functions!uniform limit of continuous functions is continuous"
    "\\(x^n\\)!converges pointwise on \\([0,1]\\)"
    "pointwise convergence"
    "\\(x^n\\) converges pointwise on \\([0,1]\\)"
    "uniform convergence!integration and"
    "convergence!pointwise convergence"
    "convergence!uniform convergence"
    "convergence!pointwise vs. uniform convergence"
    "power series!term by term integral of"
    "pointwise convergence!derivative and"
    "differentiation!of the pointwise limit of functions"
    "power series!term by term derivative of"
    "differentiation!term by term differentiation of power series"
    "sequences!Cauchy sequences"
    "convergence!of a sequence!implies Cauchy sequence"
    "sequences!Cauchy sequences!convergence of"
    "sequences!Cauchy sequences!convergence of is equivalent to the NIP"
    "sequences!Cauchy sequences!don't always converge in \\(\\QQ\\)"
    "series!Cauchy sequences!Cauchy Criterion"
    "series!Cauchy Criterion"
    "series!\\(n\\)th term test"
    "divergence!of a series!\\(n\\)th term test"
    "series!Cauchy Criterion!Strong Cauchy criterion"
    "series!Comparison Test"
    "convergence!of a series!absolute"
    "convergence!of a series!absolute convergence implies convergence"
    "series!absolute convergence of!vs. the absolute value of a series"
    "series!rearrangements"
    "series!absolute convergence of!rearrangements"
    "power series!converge inside radius of convergence"
    "power series!the radius of convergence"
    "convergence!the radius of convergence of a power series"
    "power series!a power series diverges outside it's radius of convergence"
    "Weierstrass-\\(M\\) Test"
    "power series!converge uniformly on their interval of convergence"
    "Abel, Niels Henrik!Abel's Theorem"
    "Abel's Theorem"
    "Abel, Niels Henrik!Abel's Lemma"
    "Abel's Lemma"
    "Lebesgue, Henri"
    "Cantor, Georg"
    "Cantor, Georg!and the modern view of mathematics"
    "Cantor, Georg!uniqueness of Fourier series!first theorem on"
    "Fourier Series!Cantor's first theorem on uniqueness"
    "Cantor, Georg!uniqueness of Fourier series!second theorem"
    "Fourier Series!Cantor's second theorem on uniqueness"
    "Cantor, Georg!uniqueness of Fourier series!third theorem on"
    "Fourier Series!Cantor's third theorem on uniqueness"
    "Cantor, Georg!portrait of"
    "limit!accumulation points"
    "sets!accumulation points"
    "limit!accumulation point"
    "sets!derived sets"
    "derived sets"
    "Cantor, Georg!fourth theorem on the uniqueness of Fourier series"
    "Nested Interval Property (NIP)!weak form"
    "Cantor, Georg!first proof that \\(\\RR\\) is uncountable"
    "\\(\\RR\\)!is uncountable!Cantor's first proof"
    "cardinality!countable sets"
    "countable sets!defintion of"
    "cardinality!equal cardinality"
    "\\(\\QQ\\)!is countable"
    "\\(\\QQ\\)!\\(\\QQ\\) is countable"
    "measure zero"
    "\\(\\QQ\\)!has measure zero in \\(\\RR\\)"
    "measure zero!\\(\\QQ\\) has measure zero in \\(\\RR\\)"
    "Dedekind, Richard!portrait of"
    "Dedekind, Richard"
    "Cantor, Georg!unit interval and unit square have equal cardinalty"
    "series!Geometric series!\\((0.\\bar{9})\\) converges to \\(1\\)"
    "Cantor, Georg!Cantor's Theorem"
    "countable sets!countable union of finite sets"
    "sets!countably infinite subsets"
    "Russell's Paradox"
    "Continuum Hypothesis!original"
    "Continuum Hypothesis!generalized"
    "Gödel, Kurt!portrait of"
    "number field!linearly ordered"
    "sequences!Cauchy sequences!equivalent"
    "sequences!Cauchy sequences!real numbers as Cauchy sequences"
    "sequences!Cauchy sequences!addition and multiplication of"
    "sequences!Cauchy sequences!addition of is well defined"
    "\\(\\RR\\)!addition of Cauchy sequences"
    "sequences!Cauchy sequences!zero as a Cauchy sequence"
    "\\(\\RR\\)!as Cauchy sequences!identify the multiplicative identity"
    "\\(\\RR\\)!the number \\(1\\) as a Cauchy sequence"
    "Dedekind, Richard!Dedekind cuts"
    "Dedekind, Richard!Dedekind cuts!definition of"
    "Dedekind, Richard!Dedekind cuts!ordering of"
    "Dedekind, Richard!Dedekind cuts!order properties"
    "\\(\\RR\\)!ordering Dedekind cuts"
    "Dedekind, Richard!Dedekind cuts!addition of"
    "Dedekind, Richard!Dedekind cuts!multiplication of positive cuts"
    "Dedekind, Richard!Dedekind cuts!closure of"
    "Dedekind, Richard!Dedekind cuts!multiplication of"
    "Dedekind, Richard!Dedekind cuts!absolute value"
    "Dedekind, Richard!Dedekind cuts!subtraction of"
    "Dedekind, Richard!Dedekind cuts!as sets"
    "\\(\\RR\\)!any complete, linearly ordered field is isomorphic to"
    "fields!any complete, linearly ordered field is isomorphic to \\(\\RR\\).")
   (LaTeX-add-lengths
    "qrsize"
    "previewwidth")
   (LaTeX-add-xcolor-definecolors
    "playred")
   (LaTeX-add-tcolorbox-newtcolorboxes
    '("block" "" "" "")
    '("subdisplay" "" "" "")
    '("theorem" "3" "" "")
    '("lemma" "3" "" "")
    '("corollary" "3" "" "")
    '("principle" "3" "" "")
    '("conjecture" "3" "" "")
    '("axiom" "3" "" "")
    '("definition" "2" "" "")
    '("problem" "2" "" "")
    '("example" "2" "" "")
    '("historical" "2" "" "")
    '("figureptx" "3" "" "")
    '("proof" "2" "" ""))
   (LaTeX-add-tcbuselibraries
    "skins"
    "breakable"
    "raster"
    "xparse")
   (LaTeX-add-polyglossia-langs
    '("english" "mainlanguage" "variant=usmax"))
   (LaTeX-add-enumitem-newlists
    '("referencelist" "description")))
 :latex)

